### PR TITLE
Added inner and outer contour color and sizes. Code format and removed unused import.

### PR DESCRIPTION
**Pull request by jzeferino**
I added the option to specify de the color and sizes for the inner and outer contour.
I formatted the code following android studio default guidelines.

In the future I will try to add gradient to the fill (customizable), add a vertical line to mark the starting point (customizable) and ending point of the bar.

I will like to talk to you in private, if it possible. Send me your contact.

### CODE REVIEW

**Comment by jzeferino** [comment]
screen shot 2016-07-11 at 1 52 10 pm

**Comment by jzeferino** [comment]
@jakob-grabner can you accept this PR? Thank you.

**Comment by jakob-grabner** [comment]
@jzeferino Sry, been quite busy the last weeks. I will take a look at it next week.

**Comment by jzeferino** [comment]
Thanks.

**Comment by jzeferino** [comment]
@jakob-grabner good to see it merged 👍

**Pull request merged**
